### ISSUE TITLE
Routes are not working.

### ISSUE THREAD

**Issue by manaver** [Manav32/E-commerce#1]
In the src/assets/Layout/admin/MasterLayout.js_ file when I am using route it is not working.
I use a map on the route and then display it. On localhost:3000/admin/dashboard or localhost:3000/admin/profile, it shows nothing; in the chrome console, it shows location not found.

**Comment by dunnjacoba** [comment]
I've had this issue before, utilizing BrowseRouter helped, and I think it would here to. I would like to make an attempt at it, I think the logic would work here as well.

**Comment by dunnjacoba** [comment]
#2 Please see this PR for proposed correction.

**Comment by EL02HACHMI** [comment]
1. Remove Main.js => unneeded file.
2. in App.js =>    `import React from "react";
import { BrowserRouter, Routes, Route } from "react-router-dom";
import routes from "./routes/RouteComponent";

const App = () => {
  const routeComponent = routes.map((item) => (
    <Route exact path={item.path} element={<item.element/>} key={item.id} />
  ));
  return (
    <div >
      <BrowserRouter>
      <Routes>
        {routeComponent}
      </Routes>
      </BrowserRouter>
    </div>
  );
};

export default App;
`
3.in RouteComponent.js =>
`import Dashboard from "../assests/component/Admin/Dashboard"
import MasterLayout from "./../assests/Layout/admin/MasterLayout"
import Profile from "../assests/component/Admin/Profile"

 const routes = [
    { 
        id:1,
        path: '/admin',
        exact: true,
        name: 'Admin',
        element: MasterLayout 

    },
    { 
        id:2,
        path: '/admin/dashboard',
        exact: true, 
        name: 'Dashboard', 
        element: Dashboard 
    },
    { 
        id:3,
        path: '/admin/profile', 
        exact: true,
        name: 'Profile', 
        element: Profile
    }

];

export default routes;`
4. in MasterLayout.js => `
import React from "react";
import Nav from "./nav";
import SideBar from "./Sidebar";
// import { render } from "@testing-library/react";


const MasterLayout = () => {
 
  return (
    <div>
      <Nav />
      <SideBar />
    </div>
  );
};

export default MasterLayout;
`

**Comment by manaver** [comment]
Check the new src file. There this error is showing **No routes matched location "/admin/Dashboard"**  in chrome console.
I think it is caused because of multiple routes.
